### ISSUE TITLE
With model parallel still OOM on A100-40G

### ISSUE THREAD

**Issue by LZY-the-boys** [MoFHeka/LLaMA-Megatron#1]
用4卡A100-40G，加载llama-13B：报错如下
```
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
pretrain_llama.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-06-28_17:45:54
  host      : gpu5.example.com
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 23252)
  error_file: /tmp/torchelastic_wvjb7ynx/none__3v0p5fd/attempt_0/1/error.json
  traceback : Traceback (most recent call last):
    File "/home/um202273697/.conda/envs/lla/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
      return f(*args, **kwargs)
    File "/home/um202273697/LLaMA-Megatron/llama/Megatron-LM/megatron/training.py", line 118, in pretrain
      model, optimizer, opt_param_scheduler = setup_model_and_optimizer(
    File "/home/um202273697/LLaMA-Megatron/llama/Megatron-LM/megatron/training.py", line 397, in setup_model_and_optimizer
      optimizer = get_megatron_optimizer(model, no_wd_decay_cond,
    File "/home/um202273697/LLaMA-Megatron/llama/Megatron-LM/megatron/optimizer/__init__.py", line 128, in get_megatron_optimizer
      return opt_ty(optimizer,
    File "/home/um202273697/LLaMA-Megatron/llama/Megatron-LM/megatron/optimizer/distrib_optimizer.py", line 417, in __init__
      param_buffer = torch.tensor(
  torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 11.82 GiB (GPU 1; 39.59 GiB total capacity; 29.55 GiB already allocated; 8.52 GiB free; 30.04 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF```

**Comment by MoFHeka** [comment]
把--sequence-parallel、--recompute-activations、--use-cpu-initialization、--use-distributed-optimizer都打开还是超过显存容量的话，试着调整PP、TP参数。
